### ISSUE TITLE
error with socket.io

### ISSUE THREAD

**Issue by EBugYT** [Overv/WebCraft#56]
### Hello please help me
**error is**
Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ebugyt/Downloads/WebCraft-master/server.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by SmilerRyan** [comment]
From this message, it seems you haven't installed socket.io and other dependencies.
Make sure to run ``npm install`` before starting ``node server.js``, and it should start correctly.
